{% set name = "rxn-chem-utils" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54f2973b32cdd67625bbc5441984323235b17b20e00dc5b5a83c20f64850bacb

build:
  entry_points:
    - rxn-canonicalize = rxn.chemutils.scripts.canonicalize:main
    - rxn-combine-reaction = rxn.chemutils.scripts.combine_reaction:main
    - rxn-detokenize = rxn.chemutils.scripts.detokenize:main
    - rxn-tokenize = rxn.chemutils.scripts.tokenize:main
    - rxn-rdf-to-smiles = rxn.chemutils.scripts.rdf_to_smiles:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=59.2.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.2.0
    - click >=7.0
    - rxn-utils >=1.1.9
    - rdkit

test:
  imports:
    - rxn
  commands:
    - pip check
    - rxn-canonicalize --help
    - rxn-combine-reaction --help
    - rxn-detokenize --help
    - rxn-tokenize --help
    - rxn-rdf-to-smiles --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Chemistry-related utilities
  home: https://rxn4chemistry.github.io/rxn-chemutils
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
